"use client";

import { useState } from "react";
import { FileText, Folder, FolderOpen, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Button } from "../ui/button";

interface FileNode {
  name: string;
  type: "file" | "folder";
  children?: FileNode[];
  content?: string;
}

// Mock data structure for now
const mockRepository: FileNode = {
  name: "mlops-project",
  type: "folder",
  children: [
    {
      name: "terraform",
      type: "folder",
      children: [
        {
          name: "main.tf",
          type: "file",
          content: "terraform main configuration...",
        },
        {
          name: "variables.tf",
          type: "file",
          content: "terraform variables...",
        },
        { name: "outputs.tf", type: "file", content: "terraform outputs..." },
      ],
    },
    {
      name: "docker",
      type: "folder",
      children: [
        {
          name: "Dockerfile",
          type: "file",
          content: "FROM python:3.11-slim...",
        },
        {
          name: "docker-compose.yml",
          type: "file",
          content: 'version: "3.8"...',
        },
      ],
    },
    {
      name: "src",
      type: "folder",
      children: [
        { name: "main.py", type: "file", content: "import pandas as pd..." },
        { name: "model.py", type: "file", content: "class MLModel:..." },
      ],
    },
    {
      name: "requirements.txt",
      type: "file",
      content: "pandas==2.0.0\nscikit-learn==1.3.0",
    },
    {
      name: "README.md",
      type: "file",
      content: "# MLOps Project\n\nGenerated by Agentic MLOps Platform",
    },
  ],
};

interface FileTreeProps {
  node: FileNode;
  level?: number;
  onFileSelect: (file: FileNode) => void;
}

function FileTree({ node, level = 0, onFileSelect }: FileTreeProps) {
  const [isOpen, setIsOpen] = useState(level < 2);

  const handleClick = () => {
    if (node.type === "folder") {
      setIsOpen(!isOpen);
    } else {
      onFileSelect(node);
    }
  };

  return (
    <div>
      <div
        className={`flex items-center py-1 px-2 hover:bg-accent rounded cursor-pointer`}
        style={{ paddingLeft: `${level * 16 + 8}px` }}
        onClick={handleClick}
      >
        {node.type === "folder" ? (
          isOpen ? (
            <FolderOpen className="h-4 w-4 mr-2 text-blue-500" />
          ) : (
            <Folder className="h-4 w-4 mr-2 text-blue-500" />
          )
        ) : (
          <FileText className="h-4 w-4 mr-2 text-gray-500" />
        )}
        <span className="text-sm select-none">{node.name}</span>
      </div>
      {node.type === "folder" && isOpen && node.children && (
        <div>
          {node.children.map((child, index) => (
            <FileTree
              key={`${child.name}-${index}`}
              node={child}
              level={level + 1}
              onFileSelect={onFileSelect}
            />
          ))}
        </div>
      )}
    </div>
  );
}

export default function CodeCanvas() {
  const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);

  const handleDownload = () => {
    // Mock download functionality
    alert(
      "Download functionality will be implemented with actual repository generation",
    );
  };

  return (
    <div className="flex h-full">
      {/* File Explorer */}
      <div className="w-1/3 border-r bg-muted/30">
        <Card className="h-full rounded-none border-0">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium">Files</CardTitle>
              <Button size="sm" variant="outline" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-2" />
                Download
              </Button>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="text-xs text-muted-foreground mb-2">
              Generated Repository
            </div>
            <FileTree node={mockRepository} onFileSelect={setSelectedFile} />
          </CardContent>
        </Card>
      </div>

      {/* File Content Viewer */}
      <div className="flex-1">
        <Card className="h-full rounded-none border-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">
              {selectedFile ? selectedFile.name : "No file selected"}
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0 h-full">
            {selectedFile ? (
              <div className="h-full">
                <pre className="bg-muted p-4 rounded text-sm overflow-auto h-full">
                  <code>{selectedFile.content}</code>
                </pre>
              </div>
            ) : (
              <div className="flex items-center justify-center h-full text-center">
                <div className="space-y-2">
                  <FileText className="h-12 w-12 mx-auto text-muted-foreground" />
                  <p className="text-muted-foreground">
                    Select a file to view its content
                  </p>
                  <p className="text-xs text-muted-foreground">
                    This will show the generated MLOps repository structure
                  </p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
