import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import CodeCanvas from '../code-canvas';

// Mock the lucide-react icons
jest.mock('lucide-react', () => ({
  FileText: ({ className }: { className?: string }) => <div data-testid="file-icon" className={className} />,
  Folder: () => <div data-testid="folder-icon" />,
  FolderOpen: () => <div data-testid="folder-open-icon" />,
  Download: () => <div data-testid="download-icon" />,
}));

describe('CodeCanvas', () => {
  it('renders file explorer and content viewer', () => {
    render(<CodeCanvas />);
    
    expect(screen.getByText('Files')).toBeInTheDocument();
    expect(screen.getByText('Generated Repository')).toBeInTheDocument();
    expect(screen.getByText('No file selected')).toBeInTheDocument();
  });

  it('renders repository file structure', () => {
    render(<CodeCanvas />);
    
    expect(screen.getByText('mlops-project')).toBeInTheDocument();
    expect(screen.getByText('terraform')).toBeInTheDocument();
    expect(screen.getByText('docker')).toBeInTheDocument();
    expect(screen.getByText('src')).toBeInTheDocument();
    expect(screen.getByText('requirements.txt')).toBeInTheDocument();
    expect(screen.getByText('README.md')).toBeInTheDocument();
  });

  it('shows download button', () => {
    render(<CodeCanvas />);
    
    const downloadButton = screen.getByRole('button', { name: /download/i });
    expect(downloadButton).toBeInTheDocument();
  });

  it('expands folders when clicked', async () => {
    const user = userEvent.setup();
    render(<CodeCanvas />);
    
    // The terraform folder should initially show its files (level < 2)
    expect(screen.getByText('main.tf')).toBeInTheDocument();
    expect(screen.getByText('variables.tf')).toBeInTheDocument();
    expect(screen.getByText('outputs.tf')).toBeInTheDocument();
  });

  it('selects file when clicked and shows content', async () => {
    const user = userEvent.setup();
    render(<CodeCanvas />);
    
    // Click on a file
    const fileElements = screen.getAllByText('README.md');
    await user.click(fileElements[0]);
    
    // Check that file content is displayed
    expect(screen.getByText(/# MLOps Project/)).toBeInTheDocument();
    expect(screen.getByText(/Generated by Agentic MLOps Platform/)).toBeInTheDocument();
  });

  it('shows initial empty state message', () => {
    render(<CodeCanvas />);
    
    expect(screen.getByText('Select a file to view its content')).toBeInTheDocument();
    expect(screen.getByText('This will show the generated MLOps repository structure')).toBeInTheDocument();
  });

  it('handles download button click', async () => {
    // Mock alert
    const alertSpy = jest.spyOn(window, 'alert').mockImplementation(() => {});
    
    const user = userEvent.setup();
    render(<CodeCanvas />);
    
    const downloadButton = screen.getByRole('button', { name: /download/i });
    await user.click(downloadButton);
    
    expect(alertSpy).toHaveBeenCalledWith('Download functionality will be implemented with actual repository generation');
    
    alertSpy.mockRestore();
  });
});